name: northcloud-laravel
type: php
docroot: ""
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
web_environment: []
corepack_enable: false
omit_containers: [db]
